const S = 'https://cdn.simpleicons.org';

const techIcons = {
  React: `${S}/react`,
  Vite: `${S}/vite`,
  'Tailwind CSS': `${S}/tailwindcss`,
  'Node.js': `${S}/nodedotjs`,
  Express: `${S}/express`,
  Prisma: `${S}/prisma`,
  PostgreSQL: `${S}/postgresql`,
  Python: `${S}/python`,
  FastAPI: `${S}/fastapi`,
  'D3.js': `${S}/d3dotjs`,
  Docker: `${S}/docker`,
  PyTorch: `${S}/pytorch`,
  Transformers: `${S}/huggingface`,
  Flask: `${S}/flask`,
  'Next.js': `${S}/nextdotjs`,
  TypeScript: `${S}/typescript`,
  Supabase: `${S}/supabase`,
  Redis: `${S}/redis`,
  'Cloudflare Workers': `${S}/cloudflare`,
  R2: `${S}/cloudflare`,
  TensorFlow: `${S}/tensorflow`,
  OpenCV: `${S}/opencv`,
  Zustand: `${S}/zustand`,
  'Radix UI': `${S}/radixui`,
  Zod: `${S}/zod`,
  Go: `${S}/go`,
  JavaScript: `${S}/javascript`,
  Git: `${S}/git`,
  Linux: `${S}/linux`,
  MongoDB: `${S}/mongodb`,
  MySQL: `${S}/mysql`,
  LightGBM: null,
  WebSockets: null,
  XGBoost: null,
  pgvector: null,
  MCP: null,
  SSE: null,
  JWT: null,
  'dnd-kit': null,
};

export const getTechIcon = (name) => techIcons[name] ?? null;
